# -*- coding: utf-8 -*-
"""North sussex Judo Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1htwNSyHiAgySEYA6FLs0MiUhIMhXL1He
"""

#fixed Cost of training plan
cost_of_training_plan = {
    "Beginner": 20,
    "Standard": 50,
    "Expert": 80,
}
comp_fee = 20
pvt_coaching_fee = 30

print("North Sussex Judo - monthly fee calculator")

#Athlete Info
name = input("Enter athlete name: ")
curr_weight = float(input("Enter current weight (Kg): "))
comp_weight = float(input("Enter suitable competition weight (Kg): "))
train_plan = input("Enter training plan (Beginner / standard / Expert): ")
num_of_comp = int(input("Enter the number of competitions scheduled this month: "))
pvt_coaching_hrs = float(input("Enter private coaching hours: "))

#Cost caculation
training_cost = cost_of_training_plan.get(train_plan, 0)
comp_cost = num_of_comp * comp_fee
coaching_cost = pvt_coaching_hrs * pvt_coaching_fee
total_cost = training_cost + comp_cost + coaching_cost
weight_diff = curr_weight - comp_weight

print("\n--- Monthly Summary ---")
print(f"Athlete: {name}")
print(f"Training Plan Cost: £{training_cost}")
print(f"Competition Fees: £{comp_cost}")
print(f"Private Coaching: £{coaching_cost}")
print(f"Total Monthly Cost: £{total_cost}")

# Weight comparison
if weight_diff > 0:
    print(f"Status: {weight_diff:.1f}kg over competition weight")
elif weight_diff < 0:
    print(f"Status: {abs(weight_diff):.1f}kg under competition weight")
else:
    print("Status: On target weight")



# Fixed Cost of training plan
cost_of_training_plan = {
    "Beginner": 20,
    "Standard": 50,
    "Expert": 80,
}
comp_fee = 20
pvt_coaching_fee = 30

print("North Sussex Judo - Monthly Fee Calculator")

# Athlete Info
name = input("Enter athlete name: ")
curr_weight = float(input("Enter current weight (Kg): "))
comp_weight = float(input("Enter suitable competition weight (Kg): "))
train_plan = input("Enter training plan (Beginner / Standard / Expert): ").capitalize() #capitalizing the first letter
num_of_comp = int(input("Enter the number of competitions scheduled this month: "))
pvt_coaching_hrs = float(input("Enter private coaching hours: "))

# Cost calculation
training_cost = cost_of_training_plan.get(train_plan, 0)
comp_cost = num_of_comp * comp_fee
coaching_cost = pvt_coaching_hrs * pvt_coaching_fee
total_cost = training_cost + comp_cost + coaching_cost
weight_diff = curr_weight - comp_weight

print("\n--- Monthly Summary ---")
print(f"Athlete: {name}")
print(f"Training Plan Cost: £{training_cost:,}") #adding commas to emphasize the value and make it look more effective
print(f"Competition Fees: £{comp_cost:,}")
print(f"Private Coaching: £{coaching_cost:,}")
print(f"Total Monthly Cost: £{total_cost:,}")

# Weight comparison
if weight_diff > 0:
    print(f"Status: {weight_diff:.1f}kg over competition weight")
elif weight_diff < 0:
    print(f"Status: {abs(weight_diff):.1f}kg under competition weight")
else:
    print("Status: On target weight")

#Improved code for procedural programming

# Fixed Costs
cost_of_training_plan = {
    "Beginner": 20,
    "Standard": 50,
    "Expert": 80,
}
comp_fee = 20
pvt_coaching_fee = 30

def get_athlete_info():
    print("North Sussex Judo - Monthly Fee Calculator")
    name = input("Enter athlete name: ")
    curr_weight = float(input("Enter current weight (Kg): "))
    comp_weight = float(input("Enter suitable competition weight (Kg): "))
    train_plan = input("Enter training plan (Beginner / Standard / Expert): ").capitalize()
    num_of_comp = int(input("Enter the number of competitions scheduled this month: "))
    pvt_coaching_hrs = float(input("Enter private coaching hours: "))
    return name, curr_weight, comp_weight, train_plan, num_of_comp, pvt_coaching_hrs

def calculate_fees(train_plan, num_of_comp, pvt_coaching_hrs):
    training_cost = cost_of_training_plan.get(train_plan, 0)
    comp_cost = num_of_comp * comp_fee
    coaching_cost = pvt_coaching_hrs * pvt_coaching_fee
    total_cost = training_cost + comp_cost + coaching_cost
    return training_cost, comp_cost, coaching_cost, total_cost

def calculate_weight_difference(curr_weight, comp_weight):
    return curr_weight - comp_weight

def display_summary(name, training_cost, comp_cost, coaching_cost, total_cost, weight_diff):
    print("\n--- Monthly Summary ---")
    print(f"Athlete: {name}")
    print(f"Training Plan Cost: £{training_cost:,}")
    print(f"Competition Fees: £{comp_cost:,}")
    print(f"Private Coaching: £{coaching_cost:,}")
    print(f"Total Monthly Cost: £{total_cost:,}")

    if weight_diff > 0:
        print(f"Status: {weight_diff:.1f}kg over competition weight")
    elif weight_diff < 0:
        print(f"Status: {abs(weight_diff):.1f}kg under competition weight")
    else:
        print("Status: On target weight")

# Main Program
name, curr_weight, comp_weight, train_plan, num_of_comp, pvt_coaching_hrs = get_athlete_info()
training_cost, comp_cost, coaching_cost, total_cost = calculate_fees(train_plan, num_of_comp, pvt_coaching_hrs)
weight_diff = calculate_weight_difference(curr_weight, comp_weight)
display_summary(name, training_cost, comp_cost, coaching_cost, total_cost, weight_diff)

#Improved code for Object oriented program

class Athlete:
    comp_fee = 20
    pvt_coaching_fee = 30
    cost_of_training_plan = {
        "Beginner": 20,
        "Standard": 50,
        "Expert": 80,
    }

    def __init__(self, name, curr_weight, comp_weight, train_plan, num_of_comp, pvt_coaching_hrs):
        self.name = name
        self.curr_weight = curr_weight
        self.comp_weight = comp_weight
        self.train_plan = train_plan
        self.num_of_comp = num_of_comp
        self.pvt_coaching_hrs = pvt_coaching_hrs

    def calculate_training_cost(self):
        return self.cost_of_training_plan.get(self.train_plan, 0)

    def calculate_competition_cost(self):
        return self.num_of_comp * self.comp_fee

    def calculate_coaching_cost(self):
        return self.pvt_coaching_hrs * self.pvt_coaching_fee

    def calculate_total_cost(self):
        return self.calculate_training_cost() + self.calculate_competition_cost() + self.calculate_coaching_cost()

    def weight_status(self):
        diff = self.curr_weight - self.comp_weight
        if diff > 0:
            return f"{diff:.1f}kg over competition weight"
        elif diff < 0:
            return f"{abs(diff):.1f}kg under competition weight"
        else:
            return "On target weight"

    def display_summary(self):
        print("\n--- Monthly Summary ---")
        print(f"Athlete: {self.name}")
        print(f"Training Plan Cost: £{self.calculate_training_cost():,}")
        print(f"Competition Fees: £{self.calculate_competition_cost():,}")
        print(f"Private Coaching: £{self.calculate_coaching_cost():,}")
        print(f"Total Monthly Cost: £{self.calculate_total_cost():,}")
        print(f"Status: {self.weight_status()}")


# Collecting input and using the class
print("North Sussex Judo - Monthly Fee Calculator")

name = input("Enter athlete name: ")
curr_weight = float(input("Enter current weight (Kg): "))
comp_weight = float(input("Enter suitable competition weight (Kg): "))
train_plan = input("Enter training plan (Beginner / Standard / Expert): ").capitalize()
num_of_comp = int(input("Enter the number of competitions scheduled this month: "))
pvt_coaching_hrs = float(input("Enter private coaching hours: "))

athlete = Athlete(name, curr_weight, comp_weight, train_plan, num_of_comp, pvt_coaching_hrs)
athlete.display_summary()

import ipywidgets as widgets
from IPython.display import display, clear_output

# Define the input widgets
training_plan = widgets.Dropdown(
    options=["Beginner", "Standard", "Expert"],
    description="Plan:"
)

competitions = widgets.IntText(
    description="Competitions:",
    value=0
)

coaching_hours = widgets.FloatText(
    description="Coaching Hrs:",
    value=0.0
)

calculate_button = widgets.Button(
    description="Calculate Fee",
    button_style='success'
)

result_output = widgets.Output()

# Event handler
def calculate_fee(event):
    with result_output:
        clear_output()  # Clear previous output
        plan = training_plan.value
        comps = competitions.value
        private = coaching_hours.value

        cost_lookup = {
            "Beginner": 20,
            "Standard": 50,
            "Expert": 80
        }

        base_cost = cost_lookup.get(plan, 0)
        comp_cost = comps * 20
        private_cost = private * 30
        total = base_cost + comp_cost + private_cost

        print(f"Training Plan: {plan}")
        print(f"Competition Fees: £{comp_cost:,}")
        print(f"Private Coaching: £{private_cost:,}")
        print(f"Total Monthly Cost: £{total:,}")

# Link button to handler
calculate_button.on_click(calculate_fee)

# Display UI
display(training_plan, competitions, coaching_hours, calculate_button, result_output)

#Improved code for Event driven programming

import ipywidgets as widgets
from IPython.display import display, clear_output

# Define input widgets
name_input = widgets.Text(description="Name:")
training_plan = widgets.Dropdown(
    options=["Beginner", "Standard", "Expert"],
    description="Plan:"
)
current_weight = widgets.FloatText(description="Current (kg):")
comp_weight = widgets.FloatText(description="Target (kg):")
competitions = widgets.IntText(description="Competitions:", value=0)
coaching_hours = widgets.FloatText(description="Coaching Hrs:", value=0.0)

calculate_button = widgets.Button(
    description="Calculate Fee",
    button_style='success'
)

result_output = widgets.Output()

# Event handler
def calculate_fee(event):
    with result_output:
        clear_output()  # Clear previous results

        try:
            name = name_input.value.strip()
            plan = training_plan.value
            curr_wt = current_weight.value
            target_wt = comp_weight.value
            comps = competitions.value
            private = coaching_hours.value

            # Validate name
            if not name:
                print("Please enter the athlete's name.")
                return

            # Cost calculation
            cost_lookup = {
                "Beginner": 20,
                "Standard": 50,
                "Expert": 80
            }

            base_cost = cost_lookup.get(plan, 0)
            comp_cost = comps * 20
            private_cost = private * 30
            total = base_cost + comp_cost + private_cost

            # Weight status
            diff = curr_wt - target_wt
            if diff > 0:
                status = f"{diff:.1f}kg over target weight"
            elif diff < 0:
                status = f"{abs(diff):.1f}kg under target weight"
            else:
                status = "On target weight"

            # Print result
            print(f"--- Monthly Summary for {name} ---")
            print(f"Training Plan: {plan}")
            print(f"Training Plan Cost: £{base_cost:,}")
            print(f"Competition Fees: £{comp_cost:,}")
            print(f"Private Coaching: £{private_cost:,}")
            print(f"Total Monthly Cost: £{total:,}")
            print(f"Weight Status: {status}")

        except Exception as e:
            print("Error in calculation:", str(e))

# Link button to handler
calculate_button.on_click(calculate_fee)

# Display all widgets
display(
    name_input,
    training_plan,
    current_weight,
    comp_weight,
    competitions,
    coaching_hours,
    calculate_button,
    result_output
)

#Improved algorith using IDE features
# North Sussex Judo - Monthly Fee Calculator

# Fixed Costs
COST_OF_TRAINING_PLAN = {
    "Beginner": 20,
    "Standard": 50,
    "Expert": 80,
}
COMPETITION_FEE = 20
PRIVATE_COACHING_FEE = 30

def get_valid_input(prompt, input_type=str):
    while True:
        try:
            value = input_type(input(prompt))
            return value
        except ValueError:
            print(f"Invalid input. Please enter a valid {input_type.__name__}.")

def main():
    print("North Sussex Judo - Monthly Fee Calculator\n")

    # Athlete Info
    name = input("Enter athlete name: ").strip()
    curr_weight = get_valid_input("Enter current weight (Kg): ", float)
    comp_weight = get_valid_input("Enter suitable competition weight (Kg): ", float)
    train_plan = input("Enter training plan (Beginner / Standard / Expert): ").capitalize()
    num_of_comp = get_valid_input("Enter the number of competitions scheduled this month: ", int)
    pvt_coaching_hrs = get_valid_input("Enter private coaching hours: ", float)

    # Validate training plan
    training_cost = COST_OF_TRAINING_PLAN.get(train_plan)
    if training_cost is None:
        print(f"Training plan '{train_plan}' not recognized. Setting training cost to £0.")
        training_cost = 0

    # Cost calculation
    comp_cost = num_of_comp * COMPETITION_FEE
    coaching_cost = pvt_coaching_hrs * PRIVATE_COACHING_FEE
    total_cost = training_cost + comp_cost + coaching_cost
    weight_diff = curr_weight - comp_weight

    # Output
    print("\n--- Monthly Summary ---")
    print(f"Athlete: {name}")
    print(f"Training Plan Cost: £{training_cost:,}")
    print(f"Competition Fees: £{comp_cost:,}")
    print(f"Private Coaching: £{coaching_cost:,}")
    print(f"Total Monthly Cost: £{total_cost:,}")

    # Weight comparison
    if weight_diff > 0:
        print(f"Status: {weight_diff:.1f}kg over competition weight")
    elif weight_diff < 0:
        print(f"Status: {abs(weight_diff):.1f}kg under competition weight")
    else:
        print("Status: On target weight")

if __name__ == "__main__":
    main()

# North Sussex Judo - Monthly Fee Calculator (Improved Version)

# --- Constants ---
COST_OF_TRAINING_PLAN = {
    "Beginner": 20,
    "Standard": 50,
    "Expert": 80,
}
COMPETITION_FEE = 20
PRIVATE_COACHING_FEE = 30

# --- Functions ---
def get_valid_input(prompt, input_type=str):
    """Safely gets input from the user and ensures the correct type."""
    while True:
        try:
            value = input_type(input(prompt))
            return value
        except ValueError:
            print(f"Invalid input. Please enter a valid {input_type.__name__}.")

def calculate_costs(training_plan, num_competitions, private_hours):
    """Calculates total monthly cost based on training, competitions, and coaching."""
    training_cost = COST_OF_TRAINING_PLAN.get(training_plan, 0)
    competition_cost = num_competitions * COMPETITION_FEE
    coaching_cost = private_hours * PRIVATE_COACHING_FEE
    total_cost = training_cost + competition_cost + coaching_cost
    return training_cost, competition_cost, coaching_cost, total_cost

def display_summary(name, training_cost, competition_cost, coaching_cost, total_cost, weight_status):
    """Displays the final summary for the athlete."""
    print("\n--- Monthly Summary ---")
    print(f"Athlete: {name}")
    print(f"Training Plan Cost: £{training_cost:,}")
    print(f"Competition Fees: £{competition_cost:,}")
    print(f"Private Coaching: £{coaching_cost:,}")
    print(f"Total Monthly Cost: £{total_cost:,}")
    print(f"Status: {weight_status}")

def evaluate_weight(current, competition):
    """Evaluates the weight difference for status reporting."""
    diff = current - competition
    if diff > 0:
        return f"{diff:.1f}kg over competition weight"
    elif diff < 0:
        return f"{abs(diff):.1f}kg under competition weight"
    else:
        return "On target weight"

# --- Main Program ---
def main():
    print("North Sussex Judo - Monthly Fee Calculator\n")

    # Get user inputs
    name = input("Enter athlete name: ").strip()
    curr_weight = get_valid_input("Enter current weight (Kg): ", float)
    comp_weight = get_valid_input("Enter suitable competition weight (Kg): ", float)
    train_plan = input("Enter training plan (Beginner / Standard / Expert): ").capitalize()
    num_of_comp = get_valid_input("Enter the number of competitions scheduled this month: ", int)
    pvt_coaching_hrs = get_valid_input("Enter private coaching hours: ", float)

    # Validate and calculate
    if train_plan not in COST_OF_TRAINING_PLAN:
        print(f"Warning: Training plan '{train_plan}' not recognized. Defaulting training cost to £0.")
    training_cost, comp_cost, coaching_cost, total_cost = calculate_costs(train_plan, num_of_comp, pvt_coaching_hrs)

    # Weight analysis
    weight_status = evaluate_weight(curr_weight, comp_weight)

    # Display result
    display_summary(name, training_cost, comp_cost, coaching_cost, total_cost, weight_status)

# --- Entry Point ---
if __name__ == "__main__":
    main()

# North Sussex Judo - Monthly Fee Calculator (Final Improved Version)

# --- Constants ---
COST_OF_TRAINING_PLAN = {
    "Beginner": 20,
    "Standard": 50,
    "Expert": 80,
}
COMPETITION_FEE = 20
PRIVATE_COACHING_FEE = 30

# --- Functions ---
def get_valid_input(prompt, data_type):
    """Safely gets and validates user input."""
    while True:
        try:
            return data_type(input(prompt))
        except ValueError:
            print(f"Invalid input. Please enter a valid {data_type.__name__}.")

def calculate_total_cost(training_plan, num_comps, coaching_hrs):
    """Calculates total cost based on training plan, competitions, and coaching."""
    training_cost = COST_OF_TRAINING_PLAN.get(training_plan, 0)
    comp_cost = num_comps * COMPETITION_FEE
    coaching_cost = coaching_hrs * PRIVATE_COACHING_FEE
    total_cost = training_cost + comp_cost + coaching_cost
    return training_cost, comp_cost, coaching_cost, total_cost

def evaluate_weight_status(current_weight, target_weight):
    """Evaluates athlete's weight status compared to competition weight."""
    difference = current_weight - target_weight
    if difference > 0:
        return f"{difference:.1f}kg over competition weight"
    elif difference < 0:
        return f"{abs(difference):.1f}kg under competition weight"
    else:
        return "On target weight"

def display_summary(name, training_cost, comp_cost, coaching_cost, total_cost, weight_status):
    """Displays a summary of monthly costs and athlete status."""
    print("\n--- Monthly Summary ---")
    print(f"Athlete: {name}")
    print(f"Training Plan Cost: £{training_cost}")
    print(f"Competition Fees: £{comp_cost}")
    print(f"Private Coaching: £{coaching_cost}")
    print(f"Total Monthly Cost: £{total_cost}")
    print(f"Status: {weight_status}")

# --- Main Program ---
def main():
    print("North Sussex Judo - Monthly Fee Calculator\n")

    # Input Section
    name = input("Enter athlete name: ").strip()
    curr_weight = get_valid_input("Enter current weight (Kg): ", float)
    comp_weight = get_valid_input("Enter competition weight (Kg): ", float)
    plan = input("Enter training plan (Beginner / Standard / Expert): ").capitalize()
    comps = get_valid_input("Enter number of competitions this month: ", int)
    coaching_hours = get_valid_input("Enter private coaching hours: ", float)

    # Validation
    if plan not in COST_OF_TRAINING_PLAN:
        print(f"Warning: Training plan '{plan}' not recognized. Defaulting training cost to £0.")

    # Processing
    training_cost, comp_cost, coaching_cost, total_cost = calculate_total_cost(plan, comps, coaching_hours)
    weight_status = evaluate_weight_status(curr_weight, comp_weight)

    # Output Section
    display_summary(name, training_cost, comp_cost, coaching_cost, total_cost, weight_status)

# --- Entry Point ---
if __name__ == "__main__":
    main()